<?php

namespace App\Filament\Resources\PayoutBatches\Pages;

use App\Filament\Resources\PayoutBatches\PayoutBatchResource;
use App\Services\Payouts\PayoutBatchService;
use Filament\Actions\Action;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\ViewRecord;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Auth;

class ViewPayoutBatch extends ViewRecord
{
    protected static string $resource = PayoutBatchResource::class;

    public function infolist(Schema $schema): Schema
    {
        return $schema->columns(1)->components([
            Section::make('Batch Summary')->columns(2)->schema([
                TextEntry::make('batch_number'),
                TextEntry::make('method')->badge(),
                TextEntry::make('status')->badge(),
                TextEntry::make('total_amount')->moneyWithoutTrailingZeroes('BDT'),
                TextEntry::make('total_items')->label('Items'),
                TextEntry::make('generatedBy.name')->label('Generated By'),
                TextEntry::make('approvedBy.name')->label('Approved By')->placeholder('Not yet approved'),
                TextEntry::make('approved_at')->dateTime()->placeholder('-'),
                TextEntry::make('bank_batch_reference')->label('Bank Batch Reference')->placeholder('-'),
                TextEntry::make('submitted_at')->dateTime()->placeholder('-'),
                TextEntry::make('completed_at')->dateTime()->placeholder('-'),
                TextEntry::make('exportFile')
                    ->label('Export File')
                    ->state(fn ($record): string => filled($record->export_file_path) ? 'Available' : 'Not generated yet')
                    ->url(fn ($record) => filled($record->export_file_path) ? route('payout-batches.export', $record) : null)
                    ->openUrlInNewTab(),
            ]),
        ]);
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('approve')
                ->label('Approve')
                ->icon('heroicon-o-check-circle')
                ->color('success')
                ->visible(fn (): bool => $this->record->status === 'draft' && $this->canManage())
                ->requiresConfirmation()
                ->modalDescription('This authorizes the batch for a bank/MFS file to be generated. Review every item first — this cannot be undone.')
                ->action(function (): void {
                    app(PayoutBatchService::class)->approve($this->record, Auth::user());
                    Notification::make()->success()->title('Batch approved')->send();
                }),

            Action::make('cancel')
                ->label('Cancel Batch')
                ->icon('heroicon-o-x-circle')
                ->color('danger')
                ->visible(fn (): bool => $this->record->status === 'draft' && $this->canManage())
                ->requiresConfirmation()
                ->modalDescription('Releases every item back to the pending pool so it can be included in a later batch.')
                ->action(function (): void {
                    app(PayoutBatchService::class)->cancel($this->record);
                    Notification::make()->success()->title('Batch cancelled')->send();
                }),

            Action::make('generateFile')
                ->label('Generate Export File')
                ->icon('heroicon-o-document-arrow-down')
                ->color('primary')
                ->visible(fn (): bool => $this->record->status === 'approved' && $this->canManage())
                ->requiresConfirmation()
                ->action(function (): void {
                    app(PayoutBatchService::class)->generateExportFile($this->record);
                    Notification::make()->success()->title('Export file generated')
                        ->body('Download it below and submit it through your bank\'s corporate/bulk-payment portal.')
                        ->send();
                }),

            Action::make('markSubmitted')
                ->label('Mark Submitted to Bank')
                ->icon('heroicon-o-paper-airplane')
                ->color('warning')
                ->visible(fn (): bool => $this->record->status === 'file_generated' && $this->canManage())
                ->schema([TextInput::make('bank_batch_reference')->label('Bank Batch/UTR Reference (optional)')])
                ->requiresConfirmation()
                ->action(function (array $data): void {
                    app(PayoutBatchService::class)->markSubmitted($this->record, $data['bank_batch_reference'] ?? null);
                    Notification::make()->success()->title('Batch marked submitted')
                        ->body('Reconcile each item below once the bank confirms the run.')
                        ->send();
                }),
        ];
    }

    private function canManage(): bool
    {
        return Auth::user()?->hasPermission('investments.settle') ?? false;
    }
}
