<?php

namespace App\Filament\Resources\PayoutBatches;

use App\Filament\Clusters\Investments;
use App\Filament\Resources\PayoutBatches\Pages\ListPayoutBatches;
use App\Filament\Resources\PayoutBatches\Pages\ViewPayoutBatch;
use App\Filament\Resources\PayoutBatches\RelationManagers\ItemsRelationManager;
use App\Models\PayoutBatch;
use BackedEnum;
use Filament\Actions\ViewAction;
use Filament\Resources\Resource;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/**
 * The shared bank/MFS payout batch engine — see
 * 10_INVESTOR_RESELLER_AUTO_PAYOUT_PLAN.md. Batches are never created,
 * edited, or deleted through a standard Filament form: ListPayoutBatches'
 * "Generate New Batch" header action pulls in every eligible pending
 * Investor payout, and every further state change (approve, export,
 * submit, reconcile) is a dedicated action gated by App\Services\Payouts\
 * PayoutBatchService's state machine.
 */
class PayoutBatchResource extends Resource
{
    protected static ?string $model = PayoutBatch::class;

    protected static ?string $cluster = Investments::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedBuildingLibrary;

    protected static ?string $navigationLabel = 'Payout Batches';

    protected static ?string $recordTitleAttribute = 'batch_number';

    protected static ?int $navigationSort = 4;

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->columns([
                TextColumn::make('batch_number')->searchable(),
                TextColumn::make('method')->badge(),
                TextColumn::make('status')->badge()->color(fn (string $state): string => match ($state) {
                    'draft' => 'gray',
                    'approved', 'file_generated', 'submitted_to_bank' => 'warning',
                    'completed' => 'success',
                    'partially_completed' => 'warning',
                    'failed', 'cancelled' => 'danger',
                    default => 'gray',
                }),
                TextColumn::make('total_amount')->moneyWithoutTrailingZeroes('BDT'),
                TextColumn::make('total_items')->label('Items'),
                TextColumn::make('generatedBy.name')->label('Generated By'),
                TextColumn::make('approvedBy.name')->label('Approved By')->placeholder('-'),
                TextColumn::make('submitted_at')->dateTime()->placeholder('-'),
                TextColumn::make('created_at')->dateTime()->sortable(),
            ])
            ->recordActions([ViewAction::make()]);
    }

    public static function canCreate(): bool
    {
        return false; // batches are only created via ListPayoutBatches' "Generate New Batch" action
    }

    public static function canEdit($record): bool
    {
        return false;
    }

    public static function canDelete($record): bool
    {
        return false;
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->hasPermission('investments.settle') ?? false;
    }

    public static function getRelations(): array
    {
        return [ItemsRelationManager::class];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPayoutBatches::route('/'),
            'view' => ViewPayoutBatch::route('/{record}'),
        ];
    }
}
