<?php

namespace App\Models;

use App\Models\Concerns\BelongsToCompany;
use App\Services\StockMovementService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class StockMovement extends Model
{
    use BelongsToCompany;

    public const TYPES = [
        'opening' => 'Opening',
        'purchase' => 'Purchase',
        'sale' => 'Sale',
        'return' => 'Return',
        'damage' => 'Damage',
        'adjustment' => 'Adjustment',
        'transfer' => 'Internal Transfer (shared stock)',
    ];

    /**
     * 'transfer' is auto-generated only — see
     * StockMovementService::maybeCreatePoolTransfer() — never picked from a
     * manual entry form.
     *
     * @return array<string, string>
     */
    public static function userSelectableTypes(): array
    {
        return \Illuminate\Support\Arr::except(self::TYPES, ['transfer']);
    }

    protected $fillable = [
        'company_id',
        'product_id',
        'product_variant_id',
        'type',
        'quantity',
        'reason',
        'reference_type',
        'reference_id',
        'note',
    ];

    protected $casts = [
        'quantity' => 'integer',
    ];

    protected static function booted(): void
    {
        static::creating(function (StockMovement $movement): void {
            $movement->company_id ??= $movement->product?->company_id;
        });

        static::saving(function (StockMovement $movement): void {
            app(StockMovementService::class)->prepareForSave($movement);
        });

        static::saved(function (StockMovement $movement): void {
            if ($movement->wasChanged('product_id')) {
                app(StockMovementService::class)->syncProductStock((int) $movement->getOriginal('product_id'));
            }

            $movement->applyVariantStockDelta();

            app(StockMovementService::class)->syncProductStock($movement->product_id);

            app(StockMovementService::class)->maybeCreatePoolTransfer($movement);
        });

        static::deleted(function (StockMovement $movement): void {
            $movement->restoreVariantStock();

            app(StockMovementService::class)->syncProductStock($movement->product_id);

            $movement->deleteAutoGeneratedTransfers();
        });

        static::deleting(function (StockMovement $movement): void {
            app(StockMovementService::class)->assertCanDelete($movement);
        });
    }

    /**
     * Save inside a transaction that holds a row lock on the affected
     * Product (and variant, if any) for the whole save — including the
     * `saving` hook's stock validation (a SUM over the movement ledger)
     * and the `saved` hook's stock sync. Without this lock, two concurrent
     * movements for the same product can both read the same "current
     * stock" before either commits, both pass the >= 0 check, and both
     * insert — overselling the product. Locking the Product row first
     * serializes concurrent movements for the same product so the second
     * one sees the first one's committed effect before it validates.
     */
    public function save(array $options = [])
    {
        return DB::transaction(function () use ($options) {
            $this->lockAffectedRows();

            return parent::save($options);
        });
    }

    public function delete()
    {
        return DB::transaction(function () {
            $this->lockAffectedRows();

            return parent::delete();
        });
    }

    /**
     * Locks the Product row (and variant row, if any) this movement
     * affects, always in the same order (product, then variant), so
     * concurrent movements never deadlock against each other.
     */
    protected function lockAffectedRows(): void
    {
        $productId = $this->product_id ?: $this->getOriginal('product_id');

        if ($productId) {
            Product::query()->withoutGlobalScopes()->whereKey($productId)->lockForUpdate()->first();
        }

        $variantId = $this->product_variant_id ?: $this->getOriginal('product_variant_id');

        if ($variantId) {
            ProductVariant::query()->withoutGlobalScopes()->whereKey($variantId)->lockForUpdate()->first();
        }
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function productVariant()
    {
        return $this->belongsTo(ProductVariant::class);
    }

    /**
     * Variant stock is a live counter (not ledger-derived like product
     * stock), so movements tagged with a variant apply their signed
     * quantity as a delta when created or changed.
     */
    public function applyVariantStockDelta(): void
    {
        if (! $this->product_variant_id) {
            return;
        }

        $newSigned = static::signedQuantityFor($this->type, (int) $this->quantity);
        $oldSigned = $this->wasRecentlyCreated
            ? 0
            : static::signedQuantityFor(
                (string) $this->getOriginal('type', $this->type),
                (int) $this->getOriginal('quantity', 0),
            );

        $delta = $newSigned - $oldSigned;

        if ($delta === 0) {
            return;
        }

        $variant = ProductVariant::withoutGlobalScopes()->find($this->product_variant_id);
        $variant?->update(['stock' => max(0, (int) $variant->stock + $delta)]);
    }

    public function restoreVariantStock(): void
    {
        if (! $this->product_variant_id) {
            return;
        }

        $signed = static::signedQuantityFor($this->type, (int) $this->quantity);

        if ($signed === 0) {
            return;
        }

        $variant = ProductVariant::withoutGlobalScopes()->find($this->product_variant_id);
        $variant?->update(['stock' => max(0, (int) $variant->stock - $signed)]);
    }

    /**
     * Cascade-deletes the auto-generated 'transfer' pair this movement
     * triggered (see StockMovementService::maybeCreatePoolTransfer()), so a
     * deleted/un-accounted order never leaves an orphaned shared-stock
     * mirror behind. A no-op for movements that never triggered one
     * (including 'transfer' movements themselves — nothing references a
     * transfer as its own trigger).
     */
    public function deleteAutoGeneratedTransfers(): void
    {
        static::query()
            ->withoutGlobalScopes()
            ->where('reference_type', self::class)
            ->where('reference_id', $this->getKey())
            ->get()
            ->each->delete();
    }

    public function getSignedQuantityAttribute(): int
    {
        return static::signedQuantityFor($this->type, $this->quantity);
    }

    public static function normalizeQuantity(?string $type, int $quantity): int
    {
        return app(StockMovementService::class)->normalizeQuantity($type, $quantity);
    }

    public static function signedQuantityFor(?string $type, int $quantity): int
    {
        return app(StockMovementService::class)->signedQuantityFor($type, $quantity);
    }

    public static function projectedStockFor(
        int $productId,
        string $type,
        int $quantity,
        ?int $excludingMovementId = null,
    ): int {
        return app(StockMovementService::class)->projectedStockFor($productId, $type, $quantity, $excludingMovementId);
    }

    public static function validateMovement(StockMovement $movement): void
    {
        app(StockMovementService::class)->validate($movement);
    }

    public static function syncProductStock(?int $productId): void
    {
        app(StockMovementService::class)->syncProductStock($productId);
    }
}
